---
title: "IPW"
author: "Puyin Li"
date: "2023-12-07"
output: pdf_document
---
# Data processing
```{r}
library(readr)
clean_data_test <- read_csv("/Users/paulineli/Desktop/STATS 209/Final Project/clean_data_test.csv")
dat <- clean_data_test[, -c(14, 15, 16, 17, 18, 19, 20, 21, 22)]
dat$Y <- (clean_data_test$Proj.Suc1 + clean_data_test$Proj.Suc2 + clean_data_test$Proj.Suc3
          + clean_data_test$Proj.Suc4 + clean_data_test$Proj.Suc5 + clean_data_test$Proj.Suc6
          + clean_data_test$Proj.Suc7 + clean_data_test$Proj.Suc8 + clean_data_test$Proj.Suc9) / 9
colnames(dat)[14] <- "Z"
colnames(dat)[1] <- "idx"

# make binary variables 0/1
dat$Gender <- dat$Gender - 1
dat$NGOcharacteristic <- dat$NGOcharacteristic - 1
dat$Tenure <- dat$Tenure - 1

# propensity score
dat$prop <- glm(Z ~ Gender + Education + Age + NGOcharacteristic + ProjectCharacteristic +
                  TeamSize + Tenure + ProjectDuration, family = binomial, data = dat)$fitted.values
```

# IPW Estimator 
```{r}
library(boot)
set.seed(1234)
# Horvitz–Thompson (HT) estimator
IPW_htestimator <- function(dt, indices){
  df <- dt[indices, ]
  mu1_hat = 1 / nrow(df) * sum(df$Z * df$Y / df$prop) 
  mu0_hat = 1 / nrow(df) * sum((1- df$Z) * df$Y / (1 - df$prop)) 
  tau_hat = mu1_hat - mu0_hat
  return(tau_hat)
}

boot_result <- boot(data=dat, statistic=IPW_htestimator, R = 1000)
print(boot_result)

# Hajek Estimator 
IPW_hajek_estimator <- function(dt, indices){
  df <- dt[indices, ]
  tau_hat = sum(df$Z * df$Y / df$prop) / sum(df$Z / df$prop) - 
    sum((1 - df$Z) * df$Y / (1 - df$prop)) / sum((1 - df$Z) / (1 - df$prop))
  return(tau_hat)
}

boot_result <- boot(data=dat, statistic=IPW_hajek_estimator, R = 1000)
print(boot_result)
```
